# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Erfan Khayyati"
title_separator          : "-"
name                     : &name "Erfan Khayyati"
description              : &description "CS PhD Student at Utah State University | Computer Vision & VLMs"
url                      : https://ErfanKhayyati.github.io
baseurl                  : ""
repository               : "ErfanKhayyati/ErfanKhayyati.github.io"

# Site Author
author:
  avatar           : "profile.png"
  name             : "Erfan Khayyati"
  pronouns         :
  bio              : "CS PhD Student at Utah State University. Working on Computer Vision, Vision-Language Models, and Biological Video Analysis."
  location         : "Logan, UT, USA"
  employer         : "Utah State University"
  uri              :
  email            : "Erfan.Khayyati@usu.edu"

  # Academic websites
  academia         :
  arxiv            :
  googlescholar    :
  inspire-hep      :
  impactstory      :
  orcid            :
  semantic         :
  ssrn             :
  pubmed           :
  researchgate     :
  scopus           :
  zotero           :

  # Repositories and software development
  bitbucket        :
  codepen          :
  dribbble         :
  github           : "erfankhayyati"
  kaggle           :
  stackoverflow    :

  # Social media
  linkedin         : # add your LinkedIn username here
  twitter          :
  bluesky          :
  instagram        :
  facebook         :
