# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Erfan Khayyati"
title_separator          : "-"
name                     : &name "Erfan Khayyati"
description              : &description "CS PhD Student at Utah State University | Computer Vision & VLMs"
url                      : https://ErfanKhayyati.github.io
baseurl                  : ""
repository               : "ErfanKhayyati/ErfanKhayyati.github.io"

# Site Author
author:
  avatar           : "profile.png"
  name             : "Erfan Khayyati"
  pronouns         : "he/him"
  bio              : "CS PhD Student at Utah State University."
  location         : "Logan, UT, USA"
  employer         : "Utah State University"
  email            : "Erfan.Khayyati@usu.edu"

  # Academic websites
  academia         :
  arxiv            :
  googlescholar    :  "https://scholar.google.com/citations?hl=en&user=9VN2DEYAAAAJ&authuser=1&scilu=&scisig=ACUpqDcAAAAAaMNzeJVvC5O5llfWpW8L-1CkML0&gmla=AH8HC4wYNoiwMWuAZChgXFhLzhm9Xz_gYvjYj5vwrG1ImhnLF6f56LwcZgPUZ7FmvrtdYhJMFgWoR8rET-QjBqRZWS7Z5GsC26Vsq_M&sciund=5610301763118848200"
  inspire-hep      :
  impactstory      :
  orcid            :
  semantic         :
  ssrn             :
  pubmed           :
  researchgate     :
  scopus           :
  zotero           :

  # Repositories and software development
  bitbucket        :
  codepen          :
  dribbble         :
  github           : "erfankhayyati"
  kaggle           :
  stackoverflow    :

  # Social media
  linkedin         :  "erfan-khayyati-059742206"
  twitter          :
  bluesky          :
  instagram        :
  facebook         :

  # Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - Dockerfile
  - Gemfile
  - LICENSE
  - README
  - vendor
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/
  teaching:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
timezone: Etc/UTC
